"""Top-level package for the Ezviz Cloud API helpers.

This package provides a small, typed API surface around Ezviz cloud
endpoints tailored for Home Assistant and light scripting. The
submodules contain focused functionality (client, camera/light models,
MQTT push, CAS, utilities) and this package exports the most useful
symbols for convenient imports.
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .camera import EzvizCamera
    from .cas import EzvizCAS
    from .client import EzvizClient
    from .cloud_stream import (
        VtduTokenResponse,
        copy_cloud_stream_to_mpegps,
        copy_cloud_stream_to_mpegts,
        get_cloud_stream_info,
        get_vtdu_token_v2,
        get_vtm_info,
        get_vtm_page_list,
        open_cloud_stream,
    )
    from .constants import (
        AlarmDetectHumanCar,
        BatteryCameraNewWorkMode,
        BatteryCameraWorkMode,
        DefenseModeType,
        DeviceCatagories,
        DeviceSwitchType,
        DisplayMode,
        IntelligentDetectionSmartApp,
        MessageFilterType,
        NightVisionMode,
        SoundMode,
        SupportExt,
    )
    from .exceptions import (
        AuthTestResultFailed,
        DeviceException,
        EzvizAuthTokenExpired,
        EzvizAuthVerificationCode,
        HTTPError,
        InvalidHost,
        InvalidURL,
        PyEzvizError,
    )
    from .feature import (
        day_night_mode_value,
        day_night_sensitivity_value,
        device_icr_dss_config,
        display_mode_value,
        get_algorithm_value,
        has_algorithm_subtype,
        has_osd_overlay,
        iter_algorithm_entries,
        iter_channel_algorithm_entries,
        lens_defog_config,
        lens_defog_value,
        night_vision_config,
        night_vision_duration_value,
        night_vision_luminance_value,
        night_vision_mode_value,
        night_vision_payload,
        normalize_port_security,
        optionals_mapping,
        port_security_config,
        port_security_has_port,
        port_security_port_enabled,
        resolve_channel,
        supplement_light_available,
        supplement_light_enabled,
        supplement_light_params,
        support_ext_value,
    )
    from .hcnetsdk import (
        EZVIZ_CAS_PTZ_COMMAND_MAP,
        EZVIZ_DEVICE_INFO_EX_LOGIN_PLAY_DEVICE,
        EZVIZ_HCNETUTIL_LOGIN_V40,
        EZVIZ_LAN_ACTIVITY_CHANNEL_HANDOFF,
        EZVIZ_LAN_MAIN_STREAM_TYPE,
        EZVIZ_LAN_MAIN_VIDEO_LEVEL,
        EZVIZ_LAN_PLAYBACK_VIDEO_TYPE_MAP,
        EZVIZ_LAN_PTZ_ACTION_RESET,
        EZVIZ_LAN_PTZ_ACTION_START,
        EZVIZ_LAN_PTZ_ACTION_STOP,
        EZVIZ_LAN_PTZ_COMMAND_MAP,
        EZVIZ_LAN_PTZ_PRESET_COMMANDS,
        EZVIZ_LAN_PTZ_SPEED_DEFAULT,
        EZVIZ_LAN_SUB_STREAM_TYPE,
        EZVIZ_LAN_SUB_VIDEO_LEVEL,
        EZVIZ_LOCAL_SDK_PRE_START_COMMAND,
        EZVIZ_LOCAL_SDK_PRE_START_RESPONSE,
        EZVIZ_LOCAL_SDK_PREVIEW_COMMAND,
        EZVIZ_LOCAL_SDK_PREVIEW_RESPONSE,
        EZVIZ_LOCAL_SDK_STREAM_SETUP_COMMAND,
        EZVIZ_LOCAL_SDK_STREAM_SETUP_RESPONSE,
        EZVIZ_PLAY_DATA_INFO_LOGIN_PLAY_DEVICE,
        EZVIZ_PLAYER_EXTRA_CHANNEL_NO,
        EZVIZ_PLAYER_EXTRA_DEVICE_ID,
        EZVIZ_PLAYER_EXTRA_LAN_FLAG,
        EZVIZ_PLAYER_EXTRA_LAN_USERID,
        EZVIZ_PLAYER_EXTRA_WIFI_SSID,
        EZVIZ_PLAYER_LAN_FLAG_EZLINK,
        EZVIZ_PLAYER_LAN_FLAG_HCNETSDK,
        EZVIZ_PREPLAY_SPS_TYPE,
        EZVIZ_PREVIEW_BACK_START_LAN_VIDEO_PLAY,
        EZVIZ_STREAM_INHIBIT_LAN,
        EZVIZ_STREAM_SOURCE_LIVE_MINE,
        EZVIZ_STREAM_TIMEOUT_MS,
        HCNETSDK_CLEANUP,
        HCNETSDK_CLOSE_ALARM_CHAN_V30,
        HCNETSDK_CLOSE_FORMAT_HANDLE,
        HCNETSDK_COMMAND_CANDIDATE_CONTROL,
        HCNETSDK_COMMAND_CANDIDATE_SETTINGS_LOGIN,
        HCNETSDK_DEVICE_ABILITY_BUFFER_TOO_SMALL_ERROR,
        HCNETSDK_DEVICE_ABILITY_DEFAULT_OUTPUT_BUFFER_SIZE,
        HCNETSDK_DEVICE_ABILITY_RETRY_OUTPUT_BUFFER_SIZE,
        HCNETSDK_DEVICE_ABILITY_RN_OUTPUT_BUFFER_SIZE,
        HCNETSDK_EZVIZ_CONNECT_MODE_PUT,
        HCNETSDK_EZVIZ_LAN_PASSWORD_KEY_PREFIX,
        HCNETSDK_EZVIZ_LAN_PASSWORD_PREF_SUFFIX,
        HCNETSDK_EZVIZ_NET_CONFIG_UPLOAD_PUT,
        HCNETSDK_EZVIZ_SERVICES_SWITCH_GET,
        HCNETSDK_EZVIZ_SERVICES_SWITCH_PUT,
        HCNETSDK_EZVIZ_SETTINGS_ACCOUNT_PASSWORD_ERROR,
        HCNETSDK_EZVIZ_SETTINGS_ACCOUNT_PASSWORD_LOCKED_ERROR,
        HCNETSDK_EZVIZ_SETTINGS_ERROR_BASE,
        HCNETSDK_FILECOND_FIELD_ORDER,
        HCNETSDK_FIND_CLOSE_V30,
        HCNETSDK_FIND_FILE_FAILED,
        HCNETSDK_FIND_FILE_V30,
        HCNETSDK_FIND_NEXT_FILE_EXCEPTION,
        HCNETSDK_FIND_NEXT_FILE_IS_FINDING,
        HCNETSDK_FIND_NEXT_FILE_NO_FILE,
        HCNETSDK_FIND_NEXT_FILE_NO_MORE_FILE,
        HCNETSDK_FIND_NEXT_FILE_SUCCESS,
        HCNETSDK_FIND_NEXT_FILE_V30,
        HCNETSDK_FINDDATA_V30_FIELD_ORDER,
        HCNETSDK_FORMAT_DISK,
        HCNETSDK_GET_DEVICE_ABILITY,
        HCNETSDK_GET_DOWNLOAD_POS,
        HCNETSDK_GET_DVR_CONFIG,
        HCNETSDK_GET_ERROR_MSG,
        HCNETSDK_GET_FILE_BY_NAME,
        HCNETSDK_GET_FILE_BY_TIME,
        HCNETSDK_GET_FILE_FAILED,
        HCNETSDK_GET_FORMAT_PROGRESS,
        HCNETSDK_GET_LAST_ERROR,
        HCNETSDK_GET_SDK_BUILD_VERSION,
        HCNETSDK_GET_SDK_VERSION,
        HCNETSDK_INIT,
        HCNETSDK_LOCAL_ABILITY_PARSE_CFG_FIELD_ORDER,
        HCNETSDK_LOCAL_PTZ_CFG_FIELD_ORDER,
        HCNETSDK_LOGIN_V40,
        HCNETSDK_LOGOUT_V30,
        HCNETSDK_PLAY_CONVERT,
        HCNETSDK_PLAYAUDIOVOLUME,
        HCNETSDK_PLAYBACK_BY_TIME_V40,
        HCNETSDK_PLAYBACK_CAPTURE_FILE,
        HCNETSDK_PLAYBACK_CONTROL_V40,
        HCNETSDK_PLAYBACK_FAILED,
        HCNETSDK_PLAYBACK_FILE_TYPE_ALL,
        HCNETSDK_PLAYBACK_LOCK_STATE_ALL,
        HCNETSDK_PLAYCOND_FIELD_ORDER,
        HCNETSDK_PLAYFAST,
        HCNETSDK_PLAYPAUSE,
        HCNETSDK_PLAYRESTART,
        HCNETSDK_PLAYSLOW,
        HCNETSDK_PLAYSTART,
        HCNETSDK_PLAYSTARTAUDIO,
        HCNETSDK_PLAYSTOPAUDIO,
        HCNETSDK_PTZ_CONTROL_WITH_SPEED_OTHER,
        HCNETSDK_PTZ_PRESET_OTHER,
        HCNETSDK_REALDATA_CALLBACK_V30,
        HCNETSDK_REALPLAY_V30,
        HCNETSDK_SECRET_KEY_TYPE_AES,
        HCNETSDK_SET_CONNECT_TIME,
        HCNETSDK_SET_DVR_CONFIG,
        HCNETSDK_SET_PLAY_DATA_CALLBACK,
        HCNETSDK_SET_PLAY_DATA_CALLBACK_V40,
        HCNETSDK_SET_PLAYBACK_ES_CALLBACK,
        HCNETSDK_SET_PLAYBACK_RESPONSE_CALLBACK,
        HCNETSDK_SET_PLAYBACK_SECRET_KEY,
        HCNETSDK_SET_SDK_LOCAL_CFG,
        HCNETSDK_SET_TRANS_TYPE,
        HCNETSDK_SETUP_ALARM_CHAN_V30,
        HCNETSDK_SETUP_ALARM_CHAN_V41,
        HCNETSDK_SETUPALARM_PARAM_FIELD_ORDER,
        HCNETSDK_STDXML_ANDROID_REQUEST_BUFFER_SIZE,
        HCNETSDK_STDXML_COMMAND_PORT_COMMAND_ID,
        HCNETSDK_STDXML_COMMAND_PORT_EXTRA_RESERVED_SIZE,
        HCNETSDK_STDXML_COMMAND_PORT_FLAGS,
        HCNETSDK_STDXML_COMMAND_PORT_PREFIX_SIZE,
        HCNETSDK_STDXML_CONFIG,
        HCNETSDK_STDXML_DEFAULT_OUTPUT_BUFFER_SIZE,
        HCNETSDK_STDXML_DEFAULT_STATUS_BUFFER_SIZE,
        HCNETSDK_STDXML_INPUT_FIELD_ORDER,
        HCNETSDK_STDXML_OUTPUT_FIELD_ORDER,
        HCNETSDK_STOP_GET_FILE,
        HCNETSDK_STOP_PLAYBACK,
        HCNETSDK_TCP_HEADER_LENGTH,
        HCNETSDK_TIME_FIELD_ORDER,
        SADP_ACTIVATE_DEVICE,
        SADP_CLEARUP,
        SADP_DEV_NET_PARAM_ANDROID_FIELDS,
        SADP_DEV_NET_PARAM_JNA_FIELD_ORDER,
        SADP_DEV_RET_NET_PARAM_BUFFER_SIZE,
        SADP_DEV_RET_NET_PARAM_FIELD_ORDER,
        SADP_GET_LAST_ERROR,
        SADP_GET_VERSION,
        SADP_MODIFY_DEVICE_NET_PARAM,
        SADP_MODIFY_DEVICE_NET_PARAM_V40,
        SADP_SEND_INQUIRY,
        SADP_SET_LOG_TO_FILE,
        SADP_START_V30,
        SADP_START_V40,
        SADP_STOP,
        EzvizCasDeviceInfo,
        EzvizInterleavedRtpFrame,
        EzvizInterleavedRtpFrameHeader,
        EzvizInterleavedRtpFrameWithPrefix,
        EzvizLanAccessProtocolAbility,
        EzvizLanAudioInputParam,
        EzvizLanAudioOutputVolume,
        EzvizLanAudioVideoCompressAudioChannel,
        EzvizLanAudioVideoCompressInfo,
        EzvizLanAudioVideoCompressStream,
        EzvizLanAudioVideoCompressVideoChannel,
        EzvizLanAudioVideoCompressVoiceTalkChannel,
        EzvizLanCameraParamConfig,
        EzvizLanCompressionConfig,
        EzvizLanCompressionInfoV30,
        EzvizLanDeviceConfigV40,
        EzvizLanDeviceSoftHardwareAbility,
        EzvizLanDvrConfigSummary,
        EzvizLanEzvizAccessConfig,
        EzvizLanHdConfig,
        EzvizLanHdDiskConfig,
        EzvizLanIpcFrontParameterAbility,
        EzvizLanIpcFrontParameterRange,
        EzvizLanKeyframeRequest,
        EzvizLanLiveViewParams,
        EzvizLanNetConfigV30,
        EzvizLanNetInterfaceConfig,
        EzvizLanNtpConfig,
        EzvizLanPictureConfig,
        EzvizLanPlaybackConvertAbility,
        EzvizLanPlaybackConvertResolution,
        EzvizLanPlaybackIntent,
        EzvizLanPlaybackPath,
        EzvizLanPlayDeviceLogin,
        EzvizLanPreviewPlan,
        EzvizLanPtzAbility,
        EzvizLanRecordConfigV30,
        EzvizLanRecordDayConfig,
        EzvizLanRecordScheduleSegment,
        EzvizLanSdFormatProgress,
        EzvizLanServicesSwitchState,
        EzvizLanUserConfigV30,
        EzvizLanUserConfigV30Entry,
        EzvizLanVideoPicAbility,
        EzvizLanVideoQuality,
        EzvizLanWifiApInfo,
        EzvizLanWifiConnectStatus,
        EzvizLocalAuthenticationAttrs,
        EzvizLocalPreviewRequest,
        EzvizLocalReceiverInfo,
        EzvizLocalReceiverInfoAttrs,
        EzvizLocalReceiverInfoEx,
        EzvizLocalReceiverInfoExAttrs,
        EzvizLocalSdkBodyShape,
        EzvizLocalSdkClient,
        EzvizLocalSdkExchange,
        EzvizLocalSdkFrame,
        EzvizLocalSdkFrameHeader,
        EzvizLocalSdkStreamBootstrap,
        EzvizPtzCommand,
        HcNetSdkAbility,
        HcNetSdkClientInfo,
        HcNetSdkCloseAlarmRequest,
        HcNetSdkCloseFormatHandleRequest,
        HcNetSdkCommandPortClient,
        HcNetSdkCommandPortControlResponse,
        HcNetSdkCommandPortControlTemplate,
        HcNetSdkCommandPortExchange,
        HcNetSdkCommandPortLoginChallenge,
        HcNetSdkCommandPortLoginSession,
        HcNetSdkCommandPortStreamBootstrap,
        HcNetSdkCommandTraceSummary,
        HcNetSdkDeviceAbilityRequest,
        HcNetSdkDvrCommand,
        HcNetSdkDvrConfigRequest,
        HcNetSdkFileCond,
        HcNetSdkFindCloseRequest,
        HcNetSdkFindDataV30,
        HcNetSdkFindFileRequest,
        HcNetSdkFindNextFileRequest,
        HcNetSdkFormatDiskRequest,
        HcNetSdkFormatProgressRequest,
        HcNetSdkGetDownloadPosRequest,
        HcNetSdkGetErrorMsgRequest,
        HcNetSdkGetFileByNameRequest,
        HcNetSdkGetFileByTimeRequest,
        HcNetSdkInitRequest,
        HcNetSdkLanEndpoint,
        HcNetSdkLocalCfgType,
        HcNetSdkLoginCandidate,
        HcNetSdkLogoutRequest,
        HcNetSdkNoArgRequest,
        HcNetSdkPlayBackByTimeRequest,
        HcNetSdkPlaybackCallbackRequest,
        HcNetSdkPlayBackCaptureFileRequest,
        HcNetSdkPlaybackControlCommand,
        HcNetSdkPlayBackControlRequest,
        HcNetSdkPlayBackSecretKeyRequest,
        HcNetSdkPlayCond,
        HcNetSdkPlayDataCallbackRequest,
        HcNetSdkPortProbe,
        HcNetSdkPtzCommand,
        HcNetSdkPtzControlRequest,
        HcNetSdkPtzPresetCommand,
        HcNetSdkPtzPresetRequest,
        HcNetSdkPurePythonClient,
        HcNetSdkRealDataPacket,
        HcNetSdkRealDataType,
        HcNetSdkRealPlayRequest,
        HcNetSdkSemanticLogEvent,
        HcNetSdkSetConnectTimeRequest,
        HcNetSdkSetSdkLocalCfgRequest,
        HcNetSdkSetupAlarmParam,
        HcNetSdkSetupAlarmRequest,
        HcNetSdkStdXmlConfigRequest,
        HcNetSdkStdXmlConfigResponse,
        HcNetSdkStopGetFileRequest,
        HcNetSdkStopPlayBackRequest,
        HcNetSdkTcpFrame,
        HcNetSdkTcpFrameHeader,
        HcNetSdkTcpFrameShape,
        HcNetSdkTcpPayloadShape,
        HcNetSdkTcpShapeLogRecord,
        HcNetSdkTime,
        SadpActivateDeviceRequest,
        SadpBatchResult,
        SadpDeviceInfo,
        SadpDeviceNetParam,
        SadpDeviceRetNetParam,
        SadpModifyDeviceNetParamRequest,
        SadpModifyDeviceNetParamV40Request,
        SadpNoArgRequest,
        SadpSetLogToFileRequest,
        SadpStartRequest,
        build_encrypted_ezviz_local_sdk_frame,
        build_ezviz_cas_encrypted_local_sdk_frame,
        build_ezviz_cas_ssl_local_sdk_frame,
        build_ezviz_interleaved_rtp_frame_header,
        build_ezviz_local_preview_request_body,
        build_ezviz_local_sdk_frame,
        build_ezviz_local_sdk_frame_header,
        build_ezviz_local_sdk_ssl_frame,
        build_ezviz_local_stream_setup_request_body,
        build_hcnetsdk_tcp_frame,
        classify_ezviz_local_sdk_body,
        classify_hcnetsdk_real_data_payload,
        classify_hcnetsdk_tcp_payload,
        classify_lan_ports,
        decode_hcnetsdk_command_port_login_challenge,
        decrypt_ezviz_local_sdk_body_aes_cbc,
        encrypt_ezviz_local_sdk_body_aes_cbc,
        ezviz_cas_ptz_command,
        ezviz_hcnetsdk_local_ability_parse_request,
        ezviz_hcnetsdk_local_ptz_without_recv_request,
        ezviz_lan_access_protocol_ability,
        ezviz_lan_access_protocol_ability_input,
        ezviz_lan_access_protocol_ability_request,
        ezviz_lan_audio_input_get_config_request,
        ezviz_lan_audio_input_param,
        ezviz_lan_audio_output_volume,
        ezviz_lan_audio_video_compress_info,
        ezviz_lan_audio_video_compress_info_ability_request,
        ezviz_lan_audio_video_compress_info_input,
        ezviz_lan_audio_volume_update_requests,
        ezviz_lan_audioout_volume_get_config_request,
        ezviz_lan_backlight_wdr_get_config_request,
        ezviz_lan_backlight_wdr_update_request,
        ezviz_lan_camera_param_config,
        ezviz_lan_complete_playback_path,
        ezviz_lan_compression_config,
        ezviz_lan_connect_mode_payload,
        ezviz_lan_connect_mode_put_config,
        ezviz_lan_connect_mode_put_request,
        ezviz_lan_day_night_get_config_request,
        ezviz_lan_day_night_update_request,
        ezviz_lan_device_config_v40,
        ezviz_lan_device_config_v40_request,
        ezviz_lan_dvr_config_summary,
        ezviz_lan_ezviz_access_config,
        ezviz_lan_ezviz_access_config_summary,
        ezviz_lan_ezviz_access_get_config_request,
        ezviz_lan_ezviz_access_replacement_domain,
        ezviz_lan_ezviz_access_replacement_domain_request,
        ezviz_lan_ezviz_access_set_domain_request,
        ezviz_lan_hd_config_request,
        ezviz_lan_image_display_param_ability_input,
        ezviz_lan_image_display_param_ability_request,
        ezviz_lan_ipc_front_parameter_ability,
        ezviz_lan_ipc_front_parameter_ability_request,
        ezviz_lan_live_view_params,
        ezviz_lan_local_user_password,
        ezviz_lan_login_candidates,
        ezviz_lan_net_config_and_voice_upload_payload,
        ezviz_lan_net_config_and_voice_upload_put_config,
        ezviz_lan_net_config_and_voice_upload_put_request,
        ezviz_lan_net_config_v30,
        ezviz_lan_net_config_v30_request,
        ezviz_lan_ntp_config,
        ezviz_lan_ntp_get_config_request,
        ezviz_lan_password_store_key,
        ezviz_lan_password_store_name,
        ezviz_lan_pic_config_get_request,
        ezviz_lan_pic_config_update_request,
        ezviz_lan_pic_config_v30_get_request,
        ezviz_lan_picture_config,
        ezviz_lan_play_device_login,
        ezviz_lan_play_device_login_succeeded,
        ezviz_lan_playback_condition,
        ezviz_lan_playback_convert_ability,
        ezviz_lan_playback_file_search_condition,
        ezviz_lan_playback_intent,
        ezviz_lan_playback_video_type,
        ezviz_lan_preview_plan,
        ezviz_lan_ptz_ability,
        ezviz_lan_ptz_ability_input,
        ezviz_lan_ptz_ability_request,
        ezviz_lan_ptz_control_request,
        ezviz_lan_ptz_is_preset_command,
        ezviz_lan_ptz_native_command,
        ezviz_lan_ptz_preset_request,
        ezviz_lan_ptz_request,
        ezviz_lan_record_ability_request,
        ezviz_lan_record_config_v30,
        ezviz_lan_record_config_v30_request,
        ezviz_lan_rn_device_ability_request,
        ezviz_lan_sadp_activate_batch_result,
        ezviz_lan_sadp_edit_net_param_batch_result,
        ezviz_lan_sd_format_close_request,
        ezviz_lan_sd_format_progress_request,
        ezviz_lan_sd_format_progress_result,
        ezviz_lan_sd_format_start_request,
        ezviz_lan_services_switch_get_command_port,
        ezviz_lan_services_switch_get_config,
        ezviz_lan_services_switch_get_request,
        ezviz_lan_services_switch_payload,
        ezviz_lan_services_switch_put_config,
        ezviz_lan_services_switch_put_request,
        ezviz_lan_services_switch_set_command_port,
        ezviz_lan_services_switch_set_config,
        ezviz_lan_services_switch_set_payload,
        ezviz_lan_services_switch_state,
        ezviz_lan_services_switch_state_command_port,
        ezviz_lan_services_switch_succeeded,
        ezviz_lan_services_switch_update_config,
        ezviz_lan_settings_channel_number,
        ezviz_lan_settings_error_clears_password,
        ezviz_lan_settings_error_code,
        ezviz_lan_settings_login_candidates,
        ezviz_lan_settings_login_succeeded,
        ezviz_lan_settings_updates_services_switch,
        ezviz_lan_soft_hardware_ability,
        ezviz_lan_soft_hardware_ability_request,
        ezviz_lan_time_config,
        ezviz_lan_time_get_config_request,
        ezviz_lan_user_config_v30,
        ezviz_lan_user_config_v30_summary,
        ezviz_lan_user_password_get_config_request,
        ezviz_lan_user_password_update_request,
        ezviz_lan_video_coding_get_config_request,
        ezviz_lan_video_coding_update_request,
        ezviz_lan_video_effect_get_config_request,
        ezviz_lan_video_effect_update_request,
        ezviz_lan_video_level_for_stream_type,
        ezviz_lan_video_pic_ability,
        ezviz_lan_video_pic_ability_input,
        ezviz_lan_video_pic_ability_request,
        ezviz_lan_video_qualities,
        ezviz_lan_wifi_ap_info_list,
        ezviz_lan_wifi_ap_info_list_request,
        ezviz_lan_wifi_config_summary,
        ezviz_lan_wifi_connect_status,
        ezviz_lan_wifi_connect_status_request,
        ezviz_lan_wifi_get_config_request,
        ezviz_lan_wifi_set_config_request,
        ezviz_lan_wifi_station_patch,
        ezviz_lan_wifi_work_mode_update_request,
        ezviz_local_sdk_iv,
        ezviz_local_sdk_ssl_iv,
        ezviz_native_video_level,
        hcnetsdk_cleanup_request,
        hcnetsdk_close_alarm_request,
        hcnetsdk_command_candidate_role,
        hcnetsdk_command_port_auth_word,
        hcnetsdk_command_port_control_frame,
        hcnetsdk_command_port_control_template_from_frame,
        hcnetsdk_command_port_execute_template,
        hcnetsdk_command_port_login_proof,
        hcnetsdk_command_port_login_proof_frame,
        hcnetsdk_command_port_login_request_frame,
        hcnetsdk_command_port_password_digest,
        hcnetsdk_command_port_play_login_body_tail_for_today,
        hcnetsdk_command_port_public_key_der,
        hcnetsdk_command_port_response_payload,
        hcnetsdk_device_ability_command_port_body_tail,
        hcnetsdk_device_ability_command_port_template,
        hcnetsdk_device_ability_request,
        hcnetsdk_device_ability_xml,
        hcnetsdk_dvr_config_command_port_template,
        hcnetsdk_dvr_config_get_request,
        hcnetsdk_dvr_config_set_request,
        hcnetsdk_file_search_condition,
        hcnetsdk_find_close_v30_request,
        hcnetsdk_find_file_v30_request,
        hcnetsdk_find_next_file_status,
        hcnetsdk_find_next_file_v30_request,
        hcnetsdk_get_device_ability_command_port,
        hcnetsdk_get_download_pos_request,
        hcnetsdk_get_dvr_config_command_port,
        hcnetsdk_get_error_msg_request,
        hcnetsdk_get_file_by_name_request,
        hcnetsdk_get_file_by_time_request,
        hcnetsdk_get_last_error_request,
        hcnetsdk_get_sdk_build_version_request,
        hcnetsdk_get_sdk_version_request,
        hcnetsdk_init_request,
        hcnetsdk_logout_v30_request,
        hcnetsdk_playback_by_time_v40_request,
        hcnetsdk_playback_capture_file_request,
        hcnetsdk_playback_condition,
        hcnetsdk_playback_control_v40_request,
        hcnetsdk_real_data_type_is_media,
        hcnetsdk_real_play_request,
        hcnetsdk_set_connect_time_request,
        hcnetsdk_set_play_data_callback_request,
        hcnetsdk_set_play_data_callback_v40_request,
        hcnetsdk_set_playback_es_callback_request,
        hcnetsdk_set_playback_response_callback_request,
        hcnetsdk_set_playback_secret_key_request,
        hcnetsdk_set_sdk_local_cfg_request,
        hcnetsdk_setup_alarm_v30_request,
        hcnetsdk_setup_alarm_v41_request,
        hcnetsdk_stdxml_config_command_port,
        hcnetsdk_stdxml_config_command_port_body_tail,
        hcnetsdk_stdxml_config_command_port_from_trace,
        hcnetsdk_stdxml_config_command_port_template,
        hcnetsdk_stdxml_config_request,
        hcnetsdk_stdxml_isapi_command_port,
        hcnetsdk_stdxml_isapi_request,
        hcnetsdk_stdxml_response_json,
        hcnetsdk_stop_get_file_request,
        hcnetsdk_stop_playback_request,
        hcnetsdk_time,
        hcnetsdk_time_from_datetime,
        iter_hcnetsdk_real_data_mpegps,
        iter_hcnetsdk_tcp_frame_shapes,
        parse_ezviz_interleaved_rtp_frame_header,
        parse_ezviz_local_device,
        parse_ezviz_local_sdk_frame,
        parse_ezviz_local_sdk_frame_header,
        parse_ezviz_local_sdk_xml_fields,
        parse_hcnetsdk_command_port_login_session,
        parse_hcnetsdk_semantic_log_line,
        parse_hcnetsdk_tcp_frame,
        parse_hcnetsdk_tcp_frame_header,
        parse_hcnetsdk_tcp_shape_log_line,
        parse_sadp_response,
        read_ezviz_interleaved_rtp_frame,
        read_ezviz_interleaved_rtp_frame_after_prefix,
        read_ezviz_local_sdk_frame,
        read_hcnetsdk_command_port_interleaved_frame_after_prefix,
        read_hcnetsdk_tcp_frame,
        sadp_activate_device_request,
        sadp_clearup_request,
        sadp_device_net_param,
        sadp_get_last_error_request,
        sadp_get_sadp_version_request,
        sadp_modify_device_net_param_request,
        sadp_modify_device_net_param_v40_request,
        sadp_send_inquiry_request,
        sadp_set_log_to_file_request,
        sadp_start_v30_request,
        sadp_start_v40_request,
        sadp_stop_request,
        summarize_hcnetsdk_command_trace,
    )
    from .light_bulb import EzvizLightBulb
    from .local_stream import (
        HCNETSDK_COMMAND_PORT_NATIVE_PLAN_APP_LAN_LIVE_VIEW,
        EzvizLocalSdkCredentials,
        EzvizLocalSdkMediaStream,
        EzvizLocalStreamPacket,
        HcNetSdkCommandPortGeneratedMultiSocketMediaStream,
        HcNetSdkCommandPortGeneratedMultiSocketPlan,
        HcNetSdkCommandPortGeneratedSocketStep,
        HcNetSdkCommandPortMediaStream,
        HcNetSdkCommandPortMultiSocketMediaStream,
        HcNetSdkCommandPortMultiSocketPlan,
        HcNetSdkCommandPortSocketStep,
        LocalSdkOutputFormat,
        collect_h264_idmx_annexb_after_first_clean_idr_window,
        collect_local_stream_mpegps,
        copy_hcnetsdk_real_data_to_mpegts,
        copy_local_sdk_stream_from_client,
        copy_local_stream_to_decrypted_mpegps,
        copy_local_stream_to_decrypted_mpegts,
        copy_local_stream_to_mpegps,
        copy_local_stream_to_mpegts,
        get_local_sdk_stream_credentials_from_client,
        hcnetsdk_command_port_generated_plan_from_socket_plan,
        hcnetsdk_command_port_native_lan_live_view_plan,
        open_hcnetsdk_command_port_generated_multi_socket_stream,
        open_hcnetsdk_command_port_multi_socket_stream,
        open_hcnetsdk_command_port_stream,
        open_local_sdk_stream,
        open_local_sdk_stream_from_client,
        skip_h264_annexb_initial_idr_windows,
        summarize_h264_annexb_idr_windows,
        summarize_h264_annexb_units,
        summarize_idmx_h264_local_packets,
        trim_h264_annexb_to_first_clean_idr_window,
    )
    from .models import (
        EzvizChimeMusic,
        EzvizDeviceChimeInfo,
        EzvizDeviceRecord,
        build_device_records_map,
    )
    from .mqtt import EzvizToken, MQTTClient, MqttData, ServiceUrls
    from .smart_plug import EzvizSmartPlug
    from .stream import (
        StopStreamResponse,
        StreamInfoResponse,
        StreamTransport,
        VtduInfoResponse,
        VtduStreamResponse,
        VtmChannel,
        VtmMessageCode,
        VtmPacket,
        VtmStreamClient,
        VtmTraceEvent,
        build_get_vtdu_info_request,
        build_peer_stream_request,
        build_start_stream_request,
        build_stop_stream_request,
        build_stream_info_request,
        build_stream_keepalive_request,
        build_vtm_url,
        decode_vtm_header,
        decode_vtm_packet,
        decrypt_hikvision_ps_video,
        detect_hikvision_ps_video_nalu_header_size,
        detect_transport,
        download_ezviz_cloud_replay,
        encode_vtm_packet,
        mpeg_ps_complete_prefix_length,
        mpeg_ps_decryptable_prefix_length,
        parse_get_vtdu_info_response,
        parse_peer_stream_response,
        parse_start_stream_response,
        parse_stop_stream_response,
        parse_stream_info_response,
        parse_vtm_url,
        rtp_payload,
        summarize_vtm_packet,
    )
    from .test_cam_rtsp import TestRTSPAuth

_EXPORTS = {
    "AlarmDetectHumanCar": "constants",
    "AuthTestResultFailed": "exceptions",
    "BatteryCameraNewWorkMode": "constants",
    "BatteryCameraWorkMode": "constants",
    "DefenseModeType": "constants",
    "DeviceCatagories": "constants",
    "DeviceException": "exceptions",
    "DeviceSwitchType": "constants",
    "DisplayMode": "constants",
    "EzvizAuthTokenExpired": "exceptions",
    "EzvizAuthVerificationCode": "exceptions",
    "EzvizCAS": "cas",
    "EzvizCamera": "camera",
    "EzvizChimeMusic": "models",
    "EzvizClient": "client",
    "EzvizDeviceChimeInfo": "models",
    "EzvizDeviceRecord": "models",
    "EZVIZ_LAN_MAIN_STREAM_TYPE": "hcnetsdk",
    "EZVIZ_LAN_MAIN_VIDEO_LEVEL": "hcnetsdk",
    "EZVIZ_LAN_PLAYBACK_VIDEO_TYPE_MAP": "hcnetsdk",
    "EZVIZ_LAN_PTZ_ACTION_RESET": "hcnetsdk",
    "EZVIZ_LAN_PTZ_ACTION_START": "hcnetsdk",
    "EZVIZ_LAN_PTZ_ACTION_STOP": "hcnetsdk",
    "EZVIZ_LAN_PTZ_COMMAND_MAP": "hcnetsdk",
    "EZVIZ_LAN_PTZ_PRESET_COMMANDS": "hcnetsdk",
    "EZVIZ_LAN_PTZ_SPEED_DEFAULT": "hcnetsdk",
    "EZVIZ_LAN_SUB_STREAM_TYPE": "hcnetsdk",
    "EZVIZ_LAN_SUB_VIDEO_LEVEL": "hcnetsdk",
    "EZVIZ_CAS_PTZ_COMMAND_MAP": "hcnetsdk",
    "EZVIZ_DEVICE_INFO_EX_LOGIN_PLAY_DEVICE": "hcnetsdk",
    "EZVIZ_HCNETUTIL_LOGIN_V40": "hcnetsdk",
    "EZVIZ_LAN_ACTIVITY_CHANNEL_HANDOFF": "hcnetsdk",
    "EZVIZ_PLAYER_EXTRA_CHANNEL_NO": "hcnetsdk",
    "EZVIZ_PLAYER_EXTRA_DEVICE_ID": "hcnetsdk",
    "EZVIZ_PLAYER_EXTRA_LAN_FLAG": "hcnetsdk",
    "EZVIZ_PLAYER_EXTRA_LAN_USERID": "hcnetsdk",
    "EZVIZ_PLAYER_EXTRA_WIFI_SSID": "hcnetsdk",
    "EZVIZ_PLAYER_LAN_FLAG_EZLINK": "hcnetsdk",
    "EZVIZ_PLAYER_LAN_FLAG_HCNETSDK": "hcnetsdk",
    "EZVIZ_PREVIEW_BACK_START_LAN_VIDEO_PLAY": "hcnetsdk",
    "EZVIZ_PLAY_DATA_INFO_LOGIN_PLAY_DEVICE": "hcnetsdk",
    "HCNETSDK_CLOSE_ALARM_CHAN_V30": "hcnetsdk",
    "HCNETSDK_CLOSE_FORMAT_HANDLE": "hcnetsdk",
    "HCNETSDK_EZVIZ_LAN_PASSWORD_KEY_PREFIX": "hcnetsdk",
    "HCNETSDK_EZVIZ_LAN_PASSWORD_PREF_SUFFIX": "hcnetsdk",
    "HCNETSDK_EZVIZ_CONNECT_MODE_PUT": "hcnetsdk",
    "HCNETSDK_EZVIZ_NET_CONFIG_UPLOAD_PUT": "hcnetsdk",
    "HCNETSDK_EZVIZ_SERVICES_SWITCH_GET": "hcnetsdk",
    "HCNETSDK_EZVIZ_SERVICES_SWITCH_PUT": "hcnetsdk",
    "HCNETSDK_EZVIZ_SETTINGS_ACCOUNT_PASSWORD_ERROR": "hcnetsdk",
    "HCNETSDK_EZVIZ_SETTINGS_ACCOUNT_PASSWORD_LOCKED_ERROR": "hcnetsdk",
    "HCNETSDK_EZVIZ_SETTINGS_ERROR_BASE": "hcnetsdk",
    "HCNETSDK_CLEANUP": "hcnetsdk",
    "HCNETSDK_COMMAND_CANDIDATE_CONTROL": "hcnetsdk",
    "HCNETSDK_COMMAND_CANDIDATE_SETTINGS_LOGIN": "hcnetsdk",
    "HCNETSDK_DEVICE_ABILITY_BUFFER_TOO_SMALL_ERROR": "hcnetsdk",
    "HCNETSDK_DEVICE_ABILITY_DEFAULT_OUTPUT_BUFFER_SIZE": "hcnetsdk",
    "HCNETSDK_DEVICE_ABILITY_RETRY_OUTPUT_BUFFER_SIZE": "hcnetsdk",
    "HCNETSDK_DEVICE_ABILITY_RN_OUTPUT_BUFFER_SIZE": "hcnetsdk",
    "HCNETSDK_FORMAT_DISK": "hcnetsdk",
    "HCNETSDK_GET_DOWNLOAD_POS": "hcnetsdk",
    "HCNETSDK_GET_ERROR_MSG": "hcnetsdk",
    "HCNETSDK_GET_DEVICE_ABILITY": "hcnetsdk",
    "HCNETSDK_GET_DVR_CONFIG": "hcnetsdk",
    "HCNETSDK_GET_FILE_BY_NAME": "hcnetsdk",
    "HCNETSDK_GET_FILE_BY_TIME": "hcnetsdk",
    "HCNETSDK_GET_FORMAT_PROGRESS": "hcnetsdk",
    "HCNETSDK_GET_LAST_ERROR": "hcnetsdk",
    "HCNETSDK_GET_SDK_BUILD_VERSION": "hcnetsdk",
    "HCNETSDK_GET_SDK_VERSION": "hcnetsdk",
    "HCNETSDK_INIT": "hcnetsdk",
    "HCNETSDK_LOGIN_V40": "hcnetsdk",
    "HCNETSDK_FILECOND_FIELD_ORDER": "hcnetsdk",
    "HCNETSDK_FINDDATA_V30_FIELD_ORDER": "hcnetsdk",
    "HCNETSDK_FIND_CLOSE_V30": "hcnetsdk",
    "HCNETSDK_FIND_FILE_FAILED": "hcnetsdk",
    "HCNETSDK_FIND_FILE_V30": "hcnetsdk",
    "HCNETSDK_FIND_NEXT_FILE_EXCEPTION": "hcnetsdk",
    "HCNETSDK_FIND_NEXT_FILE_IS_FINDING": "hcnetsdk",
    "HCNETSDK_FIND_NEXT_FILE_NO_FILE": "hcnetsdk",
    "HCNETSDK_FIND_NEXT_FILE_NO_MORE_FILE": "hcnetsdk",
    "HCNETSDK_FIND_NEXT_FILE_SUCCESS": "hcnetsdk",
    "HCNETSDK_FIND_NEXT_FILE_V30": "hcnetsdk",
    "HCNETSDK_LOCAL_ABILITY_PARSE_CFG_FIELD_ORDER": "hcnetsdk",
    "HCNETSDK_LOCAL_PTZ_CFG_FIELD_ORDER": "hcnetsdk",
    "HCNETSDK_LOGOUT_V30": "hcnetsdk",
    "HCNETSDK_GET_FILE_FAILED": "hcnetsdk",
    "HCNETSDK_PLAYBACK_BY_TIME_V40": "hcnetsdk",
    "HCNETSDK_PLAYBACK_CAPTURE_FILE": "hcnetsdk",
    "HCNETSDK_PLAYBACK_CONTROL_V40": "hcnetsdk",
    "HCNETSDK_PLAYBACK_FAILED": "hcnetsdk",
    "HCNETSDK_PLAYBACK_FILE_TYPE_ALL": "hcnetsdk",
    "HCNETSDK_PLAYBACK_LOCK_STATE_ALL": "hcnetsdk",
    "HCNETSDK_PLAYAUDIOVOLUME": "hcnetsdk",
    "HCNETSDK_PLAY_CONVERT": "hcnetsdk",
    "HCNETSDK_PLAYCOND_FIELD_ORDER": "hcnetsdk",
    "HCNETSDK_PLAYFAST": "hcnetsdk",
    "HCNETSDK_PLAYPAUSE": "hcnetsdk",
    "HCNETSDK_PLAYRESTART": "hcnetsdk",
    "HCNETSDK_PLAYSLOW": "hcnetsdk",
    "HCNETSDK_PLAYSTART": "hcnetsdk",
    "HCNETSDK_PLAYSTARTAUDIO": "hcnetsdk",
    "HCNETSDK_PLAYSTOPAUDIO": "hcnetsdk",
    "HCNETSDK_PTZ_CONTROL_WITH_SPEED_OTHER": "hcnetsdk",
    "HCNETSDK_PTZ_PRESET_OTHER": "hcnetsdk",
    "HCNETSDK_REALDATA_CALLBACK_V30": "hcnetsdk",
    "HCNETSDK_REALPLAY_V30": "hcnetsdk",
    "HCNETSDK_SECRET_KEY_TYPE_AES": "hcnetsdk",
    "HCNETSDK_SET_CONNECT_TIME": "hcnetsdk",
    "HCNETSDK_SET_DVR_CONFIG": "hcnetsdk",
    "HCNETSDK_SET_PLAY_DATA_CALLBACK": "hcnetsdk",
    "HCNETSDK_SET_PLAY_DATA_CALLBACK_V40": "hcnetsdk",
    "HCNETSDK_SET_PLAYBACK_ES_CALLBACK": "hcnetsdk",
    "HCNETSDK_SET_PLAYBACK_RESPONSE_CALLBACK": "hcnetsdk",
    "HCNETSDK_SET_PLAYBACK_SECRET_KEY": "hcnetsdk",
    "HCNETSDK_SET_SDK_LOCAL_CFG": "hcnetsdk",
    "HCNETSDK_SET_TRANS_TYPE": "hcnetsdk",
    "HCNETSDK_SETUPALARM_PARAM_FIELD_ORDER": "hcnetsdk",
    "HCNETSDK_SETUP_ALARM_CHAN_V30": "hcnetsdk",
    "HCNETSDK_SETUP_ALARM_CHAN_V41": "hcnetsdk",
    "HCNETSDK_STDXML_ANDROID_REQUEST_BUFFER_SIZE": "hcnetsdk",
    "HCNETSDK_STDXML_COMMAND_PORT_COMMAND_ID": "hcnetsdk",
    "HCNETSDK_STDXML_COMMAND_PORT_EXTRA_RESERVED_SIZE": "hcnetsdk",
    "HCNETSDK_STDXML_COMMAND_PORT_FLAGS": "hcnetsdk",
    "HCNETSDK_STDXML_COMMAND_PORT_PREFIX_SIZE": "hcnetsdk",
    "HCNETSDK_STDXML_DEFAULT_OUTPUT_BUFFER_SIZE": "hcnetsdk",
    "HCNETSDK_STDXML_DEFAULT_STATUS_BUFFER_SIZE": "hcnetsdk",
    "HCNETSDK_STDXML_INPUT_FIELD_ORDER": "hcnetsdk",
    "HCNETSDK_STDXML_OUTPUT_FIELD_ORDER": "hcnetsdk",
    "HCNETSDK_STDXML_CONFIG": "hcnetsdk",
    "HCNETSDK_STOP_GET_FILE": "hcnetsdk",
    "HCNETSDK_STOP_PLAYBACK": "hcnetsdk",
    "HCNETSDK_TCP_HEADER_LENGTH": "hcnetsdk",
    "HCNETSDK_TIME_FIELD_ORDER": "hcnetsdk",
    "SADP_ACTIVATE_DEVICE": "hcnetsdk",
    "SADP_DEV_NET_PARAM_ANDROID_FIELDS": "hcnetsdk",
    "SADP_DEV_NET_PARAM_JNA_FIELD_ORDER": "hcnetsdk",
    "SADP_DEV_RET_NET_PARAM_BUFFER_SIZE": "hcnetsdk",
    "SADP_DEV_RET_NET_PARAM_FIELD_ORDER": "hcnetsdk",
    "SADP_CLEARUP": "hcnetsdk",
    "SADP_GET_LAST_ERROR": "hcnetsdk",
    "SADP_GET_VERSION": "hcnetsdk",
    "SADP_MODIFY_DEVICE_NET_PARAM": "hcnetsdk",
    "SADP_MODIFY_DEVICE_NET_PARAM_V40": "hcnetsdk",
    "SADP_SEND_INQUIRY": "hcnetsdk",
    "SADP_SET_LOG_TO_FILE": "hcnetsdk",
    "SADP_START_V30": "hcnetsdk",
    "SADP_START_V40": "hcnetsdk",
    "SADP_STOP": "hcnetsdk",
    "EZVIZ_LOCAL_SDK_PRE_START_COMMAND": "hcnetsdk",
    "EZVIZ_LOCAL_SDK_PRE_START_RESPONSE": "hcnetsdk",
    "EZVIZ_LOCAL_SDK_PREVIEW_COMMAND": "hcnetsdk",
    "EZVIZ_LOCAL_SDK_PREVIEW_RESPONSE": "hcnetsdk",
    "EZVIZ_LOCAL_SDK_STREAM_SETUP_COMMAND": "hcnetsdk",
    "EZVIZ_LOCAL_SDK_STREAM_SETUP_RESPONSE": "hcnetsdk",
    "EZVIZ_PREPLAY_SPS_TYPE": "hcnetsdk",
    "EZVIZ_STREAM_INHIBIT_LAN": "hcnetsdk",
    "EZVIZ_STREAM_SOURCE_LIVE_MINE": "hcnetsdk",
    "EZVIZ_STREAM_TIMEOUT_MS": "hcnetsdk",
    "EzvizCasDeviceInfo": "hcnetsdk",
    "EzvizLanAccessProtocolAbility": "hcnetsdk",
    "EzvizLanAudioVideoCompressAudioChannel": "hcnetsdk",
    "EzvizLanAudioVideoCompressInfo": "hcnetsdk",
    "EzvizLanAudioVideoCompressStream": "hcnetsdk",
    "EzvizLanAudioVideoCompressVideoChannel": "hcnetsdk",
    "EzvizLanAudioVideoCompressVoiceTalkChannel": "hcnetsdk",
    "EzvizLanAudioInputParam": "hcnetsdk",
    "EzvizLanAudioOutputVolume": "hcnetsdk",
    "EzvizLanCameraParamConfig": "hcnetsdk",
    "EzvizLanCompressionConfig": "hcnetsdk",
    "EzvizLanCompressionInfoV30": "hcnetsdk",
    "EzvizLanDeviceConfigV40": "hcnetsdk",
    "EzvizLanDvrConfigSummary": "hcnetsdk",
    "EzvizLanEzvizAccessConfig": "hcnetsdk",
    "EzvizLanHdConfig": "hcnetsdk",
    "EzvizLanHdDiskConfig": "hcnetsdk",
    "EzvizLanIpcFrontParameterAbility": "hcnetsdk",
    "EzvizLanIpcFrontParameterRange": "hcnetsdk",
    "EzvizInterleavedRtpFrame": "hcnetsdk",
    "EzvizInterleavedRtpFrameHeader": "hcnetsdk",
    "EzvizInterleavedRtpFrameWithPrefix": "hcnetsdk",
    "EzvizLanDeviceSoftHardwareAbility": "hcnetsdk",
    "EzvizLanLiveViewParams": "hcnetsdk",
    "EzvizLanKeyframeRequest": "hcnetsdk",
    "EzvizLanPlaybackConvertAbility": "hcnetsdk",
    "EzvizLanPlaybackConvertResolution": "hcnetsdk",
    "EzvizLanPlaybackPath": "hcnetsdk",
    "EzvizLanPlaybackIntent": "hcnetsdk",
    "EzvizLanNetConfigV30": "hcnetsdk",
    "EzvizLanNetInterfaceConfig": "hcnetsdk",
    "EzvizLanNtpConfig": "hcnetsdk",
    "EzvizLanPictureConfig": "hcnetsdk",
    "EzvizLanPlayDeviceLogin": "hcnetsdk",
    "EzvizLanPreviewPlan": "hcnetsdk",
    "EzvizLanPtzAbility": "hcnetsdk",
    "EzvizLanRecordConfigV30": "hcnetsdk",
    "EzvizLanRecordDayConfig": "hcnetsdk",
    "EzvizLanRecordScheduleSegment": "hcnetsdk",
    "EzvizLanSdFormatProgress": "hcnetsdk",
    "EzvizLanWifiConnectStatus": "hcnetsdk",
    "EzvizLanServicesSwitchState": "hcnetsdk",
    "EzvizLanUserConfigV30": "hcnetsdk",
    "EzvizLanUserConfigV30Entry": "hcnetsdk",
    "EzvizLanVideoPicAbility": "hcnetsdk",
    "EzvizLanVideoQuality": "hcnetsdk",
    "EzvizLanWifiApInfo": "hcnetsdk",
    "EzvizLocalPreviewRequest": "hcnetsdk",
    "EzvizLocalReceiverInfo": "hcnetsdk",
    "EzvizLocalReceiverInfoAttrs": "hcnetsdk",
    "EzvizLocalReceiverInfoEx": "hcnetsdk",
    "EzvizLocalReceiverInfoExAttrs": "hcnetsdk",
    "EzvizLocalAuthenticationAttrs": "hcnetsdk",
    "EzvizLocalSdkClient": "hcnetsdk",
    "EzvizLocalSdkExchange": "hcnetsdk",
    "EzvizLocalSdkBodyShape": "hcnetsdk",
    "EzvizLocalSdkFrame": "hcnetsdk",
    "EzvizLocalSdkFrameHeader": "hcnetsdk",
    "EzvizLocalSdkStreamBootstrap": "hcnetsdk",
    "EzvizPtzCommand": "hcnetsdk",
    "EzvizLocalSdkCredentials": "local_stream",
    "EzvizLocalSdkMediaStream": "local_stream",
    "EzvizLocalStreamPacket": "local_stream",
    "LocalSdkOutputFormat": "local_stream",
    "HcNetSdkClientInfo": "hcnetsdk",
    "HcNetSdkCommandPortClient": "hcnetsdk",
    "HcNetSdkCommandPortControlResponse": "hcnetsdk",
    "HcNetSdkCommandPortControlTemplate": "hcnetsdk",
    "HcNetSdkCommandPortExchange": "hcnetsdk",
    "HcNetSdkCommandPortGeneratedMultiSocketPlan": "local_stream",
    "HcNetSdkCommandPortGeneratedMultiSocketMediaStream": "local_stream",
    "HcNetSdkCommandPortGeneratedSocketStep": "local_stream",
    "HCNETSDK_COMMAND_PORT_NATIVE_PLAN_APP_LAN_LIVE_VIEW": "local_stream",
    "HcNetSdkCommandPortMediaStream": "local_stream",
    "HcNetSdkCommandPortMultiSocketMediaStream": "local_stream",
    "HcNetSdkCommandPortMultiSocketPlan": "local_stream",
    "HcNetSdkCommandPortSocketStep": "local_stream",
    "HcNetSdkCommandPortStreamBootstrap": "hcnetsdk",
    "HcNetSdkCommandTraceSummary": "hcnetsdk",
    "HcNetSdkRealDataPacket": "hcnetsdk",
    "HcNetSdkRealDataType": "hcnetsdk",
    "HcNetSdkRealPlayRequest": "hcnetsdk",
    "HcNetSdkSemanticLogEvent": "hcnetsdk",
    "HcNetSdkStdXmlConfigRequest": "hcnetsdk",
    "HcNetSdkStdXmlConfigResponse": "hcnetsdk",
    "HcNetSdkTcpFrame": "hcnetsdk",
    "HcNetSdkTcpFrameHeader": "hcnetsdk",
    "HcNetSdkTcpFrameShape": "hcnetsdk",
    "HcNetSdkTcpPayloadShape": "hcnetsdk",
    "HcNetSdkTcpShapeLogRecord": "hcnetsdk",
    "SadpActivateDeviceRequest": "hcnetsdk",
    "SadpBatchResult": "hcnetsdk",
    "SadpDeviceNetParam": "hcnetsdk",
    "SadpDeviceRetNetParam": "hcnetsdk",
    "SadpNoArgRequest": "hcnetsdk",
    "SadpModifyDeviceNetParamRequest": "hcnetsdk",
    "SadpModifyDeviceNetParamV40Request": "hcnetsdk",
    "SadpSetLogToFileRequest": "hcnetsdk",
    "SadpStartRequest": "hcnetsdk",
    "EzvizLightBulb": "light_bulb",
    "EzvizSmartPlug": "smart_plug",
    "EzvizToken": "mqtt",
    "HTTPError": "exceptions",
    "IntelligentDetectionSmartApp": "constants",
    "InvalidHost": "exceptions",
    "InvalidURL": "exceptions",
    "MQTTClient": "mqtt",
    "MessageFilterType": "constants",
    "mpeg_ps_complete_prefix_length": "stream",
    "mpeg_ps_decryptable_prefix_length": "stream",
    "MqttData": "mqtt",
    "NightVisionMode": "constants",
    "PyEzvizError": "exceptions",
    "ServiceUrls": "mqtt",
    "SoundMode": "constants",
    "StreamInfoResponse": "stream",
    "StreamTransport": "stream",
    "StopStreamResponse": "stream",
    "SupportExt": "constants",
    "TestRTSPAuth": "test_cam_rtsp",
    "VtduInfoResponse": "stream",
    "VtduStreamResponse": "stream",
    "VtduTokenResponse": "cloud_stream",
    "VtmChannel": "stream",
    "VtmMessageCode": "stream",
    "VtmPacket": "stream",
    "VtmStreamClient": "stream",
    "VtmTraceEvent": "stream",
    "build_device_records_map": "models",
    "build_encrypted_ezviz_local_sdk_frame": "hcnetsdk",
    "build_ezviz_cas_encrypted_local_sdk_frame": "hcnetsdk",
    "build_ezviz_cas_ssl_local_sdk_frame": "hcnetsdk",
    "build_ezviz_interleaved_rtp_frame_header": "hcnetsdk",
    "build_hcnetsdk_tcp_frame": "hcnetsdk",
    "build_ezviz_local_preview_request_body": "hcnetsdk",
    "build_ezviz_local_sdk_frame": "hcnetsdk",
    "build_ezviz_local_sdk_frame_header": "hcnetsdk",
    "build_ezviz_local_sdk_ssl_frame": "hcnetsdk",
    "build_ezviz_local_stream_setup_request_body": "hcnetsdk",
    "classify_ezviz_local_sdk_body": "hcnetsdk",
    "classify_hcnetsdk_real_data_payload": "hcnetsdk",
    "classify_hcnetsdk_tcp_payload": "hcnetsdk",
    "build_get_vtdu_info_request": "stream",
    "build_peer_stream_request": "stream",
    "build_start_stream_request": "stream",
    "build_stop_stream_request": "stream",
    "build_stream_info_request": "stream",
    "build_stream_keepalive_request": "stream",
    "build_vtm_url": "stream",
    "day_night_mode_value": "feature",
    "day_night_sensitivity_value": "feature",
    "decode_vtm_header": "stream",
    "decode_vtm_packet": "stream",
    "decrypt_hikvision_ps_video": "stream",
    "detect_hikvision_ps_video_nalu_header_size": "stream",
    "device_icr_dss_config": "feature",
    "detect_transport": "stream",
    "display_mode_value": "feature",
    "download_ezviz_cloud_replay": "stream",
    "encode_vtm_packet": "stream",
    "decrypt_ezviz_local_sdk_body_aes_cbc": "hcnetsdk",
    "encrypt_ezviz_local_sdk_body_aes_cbc": "hcnetsdk",
    "ezviz_cas_ptz_command": "hcnetsdk",
    "ezviz_hcnetsdk_local_ability_parse_request": "hcnetsdk",
    "ezviz_hcnetsdk_local_ptz_without_recv_request": "hcnetsdk",
    "get_algorithm_value": "feature",
    "get_cloud_stream_info": "cloud_stream",
    "get_vtdu_token_v2": "cloud_stream",
    "get_vtm_info": "cloud_stream",
    "get_vtm_page_list": "cloud_stream",
    "has_algorithm_subtype": "feature",
    "has_osd_overlay": "feature",
    "HcNetSdkAbility": "hcnetsdk",
    "HcNetSdkCloseAlarmRequest": "hcnetsdk",
    "HcNetSdkCommandPortLoginChallenge": "hcnetsdk",
    "HcNetSdkCommandPortLoginSession": "hcnetsdk",
    "HcNetSdkDeviceAbilityRequest": "hcnetsdk",
    "HcNetSdkCloseFormatHandleRequest": "hcnetsdk",
    "HcNetSdkDvrConfigRequest": "hcnetsdk",
    "HcNetSdkDvrCommand": "hcnetsdk",
    "HcNetSdkFileCond": "hcnetsdk",
    "HcNetSdkFindCloseRequest": "hcnetsdk",
    "HcNetSdkFindDataV30": "hcnetsdk",
    "HcNetSdkFindFileRequest": "hcnetsdk",
    "HcNetSdkFindNextFileRequest": "hcnetsdk",
    "HcNetSdkFormatDiskRequest": "hcnetsdk",
    "HcNetSdkFormatProgressRequest": "hcnetsdk",
    "HcNetSdkGetDownloadPosRequest": "hcnetsdk",
    "HcNetSdkGetErrorMsgRequest": "hcnetsdk",
    "HcNetSdkGetFileByNameRequest": "hcnetsdk",
    "HcNetSdkGetFileByTimeRequest": "hcnetsdk",
    "HcNetSdkInitRequest": "hcnetsdk",
    "HcNetSdkLanEndpoint": "hcnetsdk",
    "HcNetSdkLoginCandidate": "hcnetsdk",
    "HcNetSdkLocalCfgType": "hcnetsdk",
    "HcNetSdkLogoutRequest": "hcnetsdk",
    "HcNetSdkNoArgRequest": "hcnetsdk",
    "HcNetSdkPlayBackByTimeRequest": "hcnetsdk",
    "HcNetSdkPlayBackCaptureFileRequest": "hcnetsdk",
    "HcNetSdkPlayBackSecretKeyRequest": "hcnetsdk",
    "HcNetSdkPlaybackCallbackRequest": "hcnetsdk",
    "HcNetSdkPlayBackControlRequest": "hcnetsdk",
    "HcNetSdkPlayCond": "hcnetsdk",
    "HcNetSdkPlaybackControlCommand": "hcnetsdk",
    "HcNetSdkPlayDataCallbackRequest": "hcnetsdk",
    "HcNetSdkPortProbe": "hcnetsdk",
    "HcNetSdkPtzCommand": "hcnetsdk",
    "HcNetSdkPtzControlRequest": "hcnetsdk",
    "HcNetSdkPtzPresetCommand": "hcnetsdk",
    "HcNetSdkPtzPresetRequest": "hcnetsdk",
    "HcNetSdkPurePythonClient": "hcnetsdk",
    "HcNetSdkSetConnectTimeRequest": "hcnetsdk",
    "HcNetSdkSetSdkLocalCfgRequest": "hcnetsdk",
    "HcNetSdkSetupAlarmParam": "hcnetsdk",
    "HcNetSdkSetupAlarmRequest": "hcnetsdk",
    "HcNetSdkStopGetFileRequest": "hcnetsdk",
    "HcNetSdkStopPlayBackRequest": "hcnetsdk",
    "HcNetSdkTime": "hcnetsdk",
    "iter_algorithm_entries": "feature",
    "iter_channel_algorithm_entries": "feature",
    "lens_defog_config": "feature",
    "lens_defog_value": "feature",
    "night_vision_config": "feature",
    "night_vision_duration_value": "feature",
    "night_vision_luminance_value": "feature",
    "night_vision_mode_value": "feature",
    "night_vision_payload": "feature",
    "normalize_port_security": "feature",
    "optionals_mapping": "feature",
    "ezviz_lan_access_protocol_ability": "hcnetsdk",
    "ezviz_lan_access_protocol_ability_input": "hcnetsdk",
    "ezviz_lan_access_protocol_ability_request": "hcnetsdk",
    "ezviz_lan_audio_input_get_config_request": "hcnetsdk",
    "ezviz_lan_audio_input_param": "hcnetsdk",
    "ezviz_lan_audio_video_compress_info": "hcnetsdk",
    "ezviz_lan_audio_video_compress_info_input": "hcnetsdk",
    "ezviz_lan_audio_video_compress_info_ability_request": "hcnetsdk",
    "ezviz_lan_audio_output_volume": "hcnetsdk",
    "ezviz_lan_audio_volume_update_requests": "hcnetsdk",
    "ezviz_lan_audioout_volume_get_config_request": "hcnetsdk",
    "ezviz_lan_backlight_wdr_get_config_request": "hcnetsdk",
    "ezviz_lan_backlight_wdr_update_request": "hcnetsdk",
    "ezviz_lan_camera_param_config": "hcnetsdk",
    "ezviz_lan_complete_playback_path": "hcnetsdk",
    "ezviz_lan_compression_config": "hcnetsdk",
    "ezviz_lan_connect_mode_payload": "hcnetsdk",
    "ezviz_lan_connect_mode_put_config": "hcnetsdk",
    "ezviz_lan_connect_mode_put_request": "hcnetsdk",
    "ezviz_lan_day_night_get_config_request": "hcnetsdk",
    "ezviz_lan_day_night_update_request": "hcnetsdk",
    "ezviz_lan_device_config_v40": "hcnetsdk",
    "ezviz_lan_device_config_v40_request": "hcnetsdk",
    "ezviz_lan_dvr_config_summary": "hcnetsdk",
    "ezviz_lan_ezviz_access_config": "hcnetsdk",
    "ezviz_lan_ezviz_access_config_summary": "hcnetsdk",
    "ezviz_lan_ezviz_access_get_config_request": "hcnetsdk",
    "ezviz_lan_ezviz_access_replacement_domain": "hcnetsdk",
    "ezviz_lan_ezviz_access_replacement_domain_request": "hcnetsdk",
    "ezviz_lan_ezviz_access_set_domain_request": "hcnetsdk",
    "ezviz_lan_hd_config_request": "hcnetsdk",
    "ezviz_lan_live_view_params": "hcnetsdk",
    "ezviz_lan_login_candidates": "hcnetsdk",
    "ezviz_lan_local_user_password": "hcnetsdk",
    "ezviz_lan_image_display_param_ability_input": "hcnetsdk",
    "ezviz_lan_image_display_param_ability_request": "hcnetsdk",
    "ezviz_lan_ipc_front_parameter_ability": "hcnetsdk",
    "ezviz_lan_ipc_front_parameter_ability_request": "hcnetsdk",
    "ezviz_lan_net_config_and_voice_upload_payload": "hcnetsdk",
    "ezviz_lan_net_config_and_voice_upload_put_config": "hcnetsdk",
    "ezviz_lan_net_config_and_voice_upload_put_request": "hcnetsdk",
    "ezviz_lan_net_config_v30": "hcnetsdk",
    "ezviz_lan_net_config_v30_request": "hcnetsdk",
    "ezviz_lan_ntp_config": "hcnetsdk",
    "ezviz_lan_ntp_get_config_request": "hcnetsdk",
    "ezviz_lan_password_store_key": "hcnetsdk",
    "ezviz_lan_password_store_name": "hcnetsdk",
    "ezviz_lan_play_device_login": "hcnetsdk",
    "ezviz_lan_play_device_login_succeeded": "hcnetsdk",
    "ezviz_lan_playback_intent": "hcnetsdk",
    "ezviz_lan_playback_condition": "hcnetsdk",
    "ezviz_lan_playback_convert_ability": "hcnetsdk",
    "ezviz_lan_playback_file_search_condition": "hcnetsdk",
    "ezviz_lan_playback_video_type": "hcnetsdk",
    "ezviz_lan_preview_plan": "hcnetsdk",
    "ezviz_lan_pic_config_get_request": "hcnetsdk",
    "ezviz_lan_pic_config_v30_get_request": "hcnetsdk",
    "ezviz_lan_pic_config_update_request": "hcnetsdk",
    "ezviz_lan_picture_config": "hcnetsdk",
    "ezviz_lan_ptz_ability": "hcnetsdk",
    "ezviz_lan_ptz_ability_input": "hcnetsdk",
    "ezviz_lan_ptz_ability_request": "hcnetsdk",
    "ezviz_lan_ptz_control_request": "hcnetsdk",
    "ezviz_lan_ptz_is_preset_command": "hcnetsdk",
    "ezviz_lan_ptz_native_command": "hcnetsdk",
    "ezviz_lan_ptz_preset_request": "hcnetsdk",
    "ezviz_lan_ptz_request": "hcnetsdk",
    "ezviz_lan_record_ability_request": "hcnetsdk",
    "ezviz_lan_record_config_v30": "hcnetsdk",
    "ezviz_lan_record_config_v30_request": "hcnetsdk",
    "ezviz_lan_rn_device_ability_request": "hcnetsdk",
    "ezviz_lan_sd_format_close_request": "hcnetsdk",
    "ezviz_lan_sd_format_progress_request": "hcnetsdk",
    "ezviz_lan_sd_format_progress_result": "hcnetsdk",
    "ezviz_lan_sd_format_start_request": "hcnetsdk",
    "ezviz_lan_sadp_activate_batch_result": "hcnetsdk",
    "ezviz_lan_sadp_edit_net_param_batch_result": "hcnetsdk",
    "ezviz_lan_services_switch_get_config": "hcnetsdk",
    "ezviz_lan_services_switch_get_command_port": "hcnetsdk",
    "ezviz_lan_services_switch_get_request": "hcnetsdk",
    "ezviz_lan_services_switch_payload": "hcnetsdk",
    "ezviz_lan_services_switch_put_config": "hcnetsdk",
    "ezviz_lan_services_switch_put_request": "hcnetsdk",
    "ezviz_lan_services_switch_set_config": "hcnetsdk",
    "ezviz_lan_services_switch_set_command_port": "hcnetsdk",
    "ezviz_lan_services_switch_set_payload": "hcnetsdk",
    "ezviz_lan_services_switch_succeeded": "hcnetsdk",
    "ezviz_lan_services_switch_state": "hcnetsdk",
    "ezviz_lan_services_switch_state_command_port": "hcnetsdk",
    "ezviz_lan_services_switch_update_config": "hcnetsdk",
    "ezviz_lan_settings_error_clears_password": "hcnetsdk",
    "ezviz_lan_settings_error_code": "hcnetsdk",
    "ezviz_lan_settings_channel_number": "hcnetsdk",
    "ezviz_lan_settings_login_candidates": "hcnetsdk",
    "ezviz_lan_settings_login_succeeded": "hcnetsdk",
    "ezviz_lan_settings_updates_services_switch": "hcnetsdk",
    "ezviz_lan_soft_hardware_ability": "hcnetsdk",
    "ezviz_lan_soft_hardware_ability_request": "hcnetsdk",
    "ezviz_lan_time_config": "hcnetsdk",
    "ezviz_lan_time_get_config_request": "hcnetsdk",
    "ezviz_lan_user_config_v30": "hcnetsdk",
    "ezviz_lan_user_config_v30_summary": "hcnetsdk",
    "ezviz_lan_user_password_get_config_request": "hcnetsdk",
    "ezviz_lan_user_password_update_request": "hcnetsdk",
    "ezviz_lan_video_pic_ability": "hcnetsdk",
    "ezviz_lan_video_pic_ability_input": "hcnetsdk",
    "ezviz_lan_video_pic_ability_request": "hcnetsdk",
    "ezviz_lan_video_coding_get_config_request": "hcnetsdk",
    "ezviz_lan_video_coding_update_request": "hcnetsdk",
    "ezviz_lan_video_effect_get_config_request": "hcnetsdk",
    "ezviz_lan_video_effect_update_request": "hcnetsdk",
    "ezviz_lan_video_qualities": "hcnetsdk",
    "ezviz_lan_video_level_for_stream_type": "hcnetsdk",
    "ezviz_lan_hd_config": "hcnetsdk",
    "ezviz_lan_wifi_ap_info_list": "hcnetsdk",
    "ezviz_lan_wifi_ap_info_list_request": "hcnetsdk",
    "ezviz_lan_wifi_config_summary": "hcnetsdk",
    "ezviz_lan_wifi_connect_status": "hcnetsdk",
    "ezviz_lan_wifi_connect_status_request": "hcnetsdk",
    "ezviz_lan_wifi_get_config_request": "hcnetsdk",
    "ezviz_lan_wifi_set_config_request": "hcnetsdk",
    "ezviz_lan_wifi_station_patch": "hcnetsdk",
    "ezviz_lan_wifi_work_mode_update_request": "hcnetsdk",
    "ezviz_local_sdk_iv": "hcnetsdk",
    "ezviz_local_sdk_ssl_iv": "hcnetsdk",
    "ezviz_native_video_level": "hcnetsdk",
    "decode_hcnetsdk_command_port_login_challenge": "hcnetsdk",
    "hcnetsdk_real_data_type_is_media": "hcnetsdk",
    "hcnetsdk_command_candidate_role": "hcnetsdk",
    "hcnetsdk_command_port_auth_word": "hcnetsdk",
    "hcnetsdk_command_port_control_frame": "hcnetsdk",
    "hcnetsdk_command_port_control_template_from_frame": "hcnetsdk",
    "hcnetsdk_command_port_execute_template": "hcnetsdk",
    "hcnetsdk_command_port_login_proof": "hcnetsdk",
    "hcnetsdk_command_port_login_proof_frame": "hcnetsdk",
    "hcnetsdk_command_port_login_request_frame": "hcnetsdk",
    "hcnetsdk_command_port_password_digest": "hcnetsdk",
    "hcnetsdk_command_port_play_login_body_tail_for_today": "hcnetsdk",
    "hcnetsdk_command_port_public_key_der": "hcnetsdk",
    "hcnetsdk_command_port_response_payload": "hcnetsdk",
    "hcnetsdk_cleanup_request": "hcnetsdk",
    "hcnetsdk_close_alarm_request": "hcnetsdk",
    "hcnetsdk_device_ability_command_port_body_tail": "hcnetsdk",
    "hcnetsdk_device_ability_command_port_template": "hcnetsdk",
    "hcnetsdk_device_ability_request": "hcnetsdk",
    "hcnetsdk_device_ability_xml": "hcnetsdk",
    "hcnetsdk_dvr_config_command_port_template": "hcnetsdk",
    "hcnetsdk_dvr_config_get_request": "hcnetsdk",
    "hcnetsdk_dvr_config_set_request": "hcnetsdk",
    "hcnetsdk_file_search_condition": "hcnetsdk",
    "hcnetsdk_find_close_v30_request": "hcnetsdk",
    "hcnetsdk_find_file_v30_request": "hcnetsdk",
    "hcnetsdk_find_next_file_status": "hcnetsdk",
    "hcnetsdk_find_next_file_v30_request": "hcnetsdk",
    "hcnetsdk_get_download_pos_request": "hcnetsdk",
    "hcnetsdk_get_device_ability_command_port": "hcnetsdk",
    "hcnetsdk_get_dvr_config_command_port": "hcnetsdk",
    "hcnetsdk_get_error_msg_request": "hcnetsdk",
    "hcnetsdk_get_file_by_name_request": "hcnetsdk",
    "hcnetsdk_get_file_by_time_request": "hcnetsdk",
    "hcnetsdk_get_last_error_request": "hcnetsdk",
    "hcnetsdk_get_sdk_build_version_request": "hcnetsdk",
    "hcnetsdk_get_sdk_version_request": "hcnetsdk",
    "hcnetsdk_init_request": "hcnetsdk",
    "hcnetsdk_logout_v30_request": "hcnetsdk",
    "hcnetsdk_playback_by_time_v40_request": "hcnetsdk",
    "hcnetsdk_playback_capture_file_request": "hcnetsdk",
    "hcnetsdk_playback_condition": "hcnetsdk",
    "hcnetsdk_playback_control_v40_request": "hcnetsdk",
    "hcnetsdk_real_play_request": "hcnetsdk",
    "hcnetsdk_set_connect_time_request": "hcnetsdk",
    "hcnetsdk_set_play_data_callback_request": "hcnetsdk",
    "hcnetsdk_set_play_data_callback_v40_request": "hcnetsdk",
    "hcnetsdk_set_playback_es_callback_request": "hcnetsdk",
    "hcnetsdk_set_playback_response_callback_request": "hcnetsdk",
    "hcnetsdk_set_playback_secret_key_request": "hcnetsdk",
    "hcnetsdk_set_sdk_local_cfg_request": "hcnetsdk",
    "hcnetsdk_setup_alarm_v30_request": "hcnetsdk",
    "hcnetsdk_setup_alarm_v41_request": "hcnetsdk",
    "hcnetsdk_stdxml_config_command_port": "hcnetsdk",
    "hcnetsdk_stdxml_config_command_port_from_trace": "hcnetsdk",
    "hcnetsdk_stdxml_config_command_port_body_tail": "hcnetsdk",
    "hcnetsdk_stdxml_config_command_port_template": "hcnetsdk",
    "hcnetsdk_stdxml_config_request": "hcnetsdk",
    "hcnetsdk_stdxml_isapi_command_port": "hcnetsdk",
    "hcnetsdk_stdxml_isapi_request": "hcnetsdk",
    "hcnetsdk_stdxml_response_json": "hcnetsdk",
    "hcnetsdk_stop_get_file_request": "hcnetsdk",
    "hcnetsdk_stop_playback_request": "hcnetsdk",
    "hcnetsdk_time": "hcnetsdk",
    "hcnetsdk_time_from_datetime": "hcnetsdk",
    "iter_hcnetsdk_real_data_mpegps": "hcnetsdk",
    "iter_hcnetsdk_tcp_frame_shapes": "hcnetsdk",
    "parse_ezviz_local_device": "hcnetsdk",
    "parse_ezviz_local_sdk_frame": "hcnetsdk",
    "parse_ezviz_local_sdk_frame_header": "hcnetsdk",
    "parse_ezviz_local_sdk_xml_fields": "hcnetsdk",
    "parse_hcnetsdk_tcp_frame": "hcnetsdk",
    "parse_hcnetsdk_tcp_frame_header": "hcnetsdk",
    "parse_hcnetsdk_command_port_login_session": "hcnetsdk",
    "parse_hcnetsdk_semantic_log_line": "hcnetsdk",
    "parse_hcnetsdk_tcp_shape_log_line": "hcnetsdk",
    "summarize_hcnetsdk_command_trace": "hcnetsdk",
    "parse_ezviz_interleaved_rtp_frame_header": "hcnetsdk",
    "parse_get_vtdu_info_response": "stream",
    "parse_peer_stream_response": "stream",
    "parse_start_stream_response": "stream",
    "parse_stop_stream_response": "stream",
    "parse_stream_info_response": "stream",
    "parse_sadp_response": "hcnetsdk",
    "parse_vtm_url": "stream",
    "open_cloud_stream": "cloud_stream",
    "port_security_config": "feature",
    "port_security_has_port": "feature",
    "port_security_port_enabled": "feature",
    "resolve_channel": "feature",
    "rtp_payload": "stream",
    "read_ezviz_interleaved_rtp_frame": "hcnetsdk",
    "read_ezviz_interleaved_rtp_frame_after_prefix": "hcnetsdk",
    "read_ezviz_local_sdk_frame": "hcnetsdk",
    "read_hcnetsdk_command_port_interleaved_frame_after_prefix": "hcnetsdk",
    "read_hcnetsdk_tcp_frame": "hcnetsdk",
    "sadp_activate_device_request": "hcnetsdk",
    "sadp_clearup_request": "hcnetsdk",
    "sadp_device_net_param": "hcnetsdk",
    "sadp_get_last_error_request": "hcnetsdk",
    "sadp_get_sadp_version_request": "hcnetsdk",
    "sadp_modify_device_net_param_request": "hcnetsdk",
    "sadp_modify_device_net_param_v40_request": "hcnetsdk",
    "sadp_send_inquiry_request": "hcnetsdk",
    "sadp_set_log_to_file_request": "hcnetsdk",
    "sadp_start_v30_request": "hcnetsdk",
    "sadp_start_v40_request": "hcnetsdk",
    "sadp_stop_request": "hcnetsdk",
    "SadpDeviceInfo": "hcnetsdk",
    "summarize_vtm_packet": "stream",
    "supplement_light_available": "feature",
    "supplement_light_enabled": "feature",
    "supplement_light_params": "feature",
    "support_ext_value": "feature",
    "classify_lan_ports": "hcnetsdk",
    "collect_local_stream_mpegps": "local_stream",
    "copy_hcnetsdk_real_data_to_mpegts": "local_stream",
    "copy_cloud_stream_to_mpegps": "cloud_stream",
    "copy_cloud_stream_to_mpegts": "cloud_stream",
    "copy_local_sdk_stream_from_client": "local_stream",
    "copy_local_stream_to_decrypted_mpegps": "local_stream",
    "copy_local_stream_to_decrypted_mpegts": "local_stream",
    "copy_local_stream_to_mpegps": "local_stream",
    "copy_local_stream_to_mpegts": "local_stream",
    "collect_h264_idmx_annexb_after_first_clean_idr_window": "local_stream",
    "get_local_sdk_stream_credentials_from_client": "local_stream",
    "hcnetsdk_command_port_generated_plan_from_socket_plan": "local_stream",
    "hcnetsdk_command_port_native_lan_live_view_plan": "local_stream",
    "open_hcnetsdk_command_port_generated_multi_socket_stream": "local_stream",
    "open_hcnetsdk_command_port_multi_socket_stream": "local_stream",
    "open_hcnetsdk_command_port_stream": "local_stream",
    "open_local_sdk_stream": "local_stream",
    "open_local_sdk_stream_from_client": "local_stream",
    "summarize_h264_annexb_units": "local_stream",
    "summarize_h264_annexb_idr_windows": "local_stream",
    "skip_h264_annexb_initial_idr_windows": "local_stream",
    "summarize_idmx_h264_local_packets": "local_stream",
    "trim_h264_annexb_to_first_clean_idr_window": "local_stream",
}

__all__ = list(_EXPORTS)


def __getattr__(name: str) -> Any:
    """Lazily resolve package-level exports from their owning modules."""

    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    module = import_module(f"{__name__}.{_EXPORTS[name]}")
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return module attributes including lazy exports."""

    return sorted((*globals(), *__all__))
